In [9]:
import streamlit as st
import pandas as pd
import pickle
import io
import os
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler, RobustScaler

In [10]:
df_pre = pd.read_csv(r"C:\Users\DELL\Downloads\Personal_Projects\Classification_Customer_Churn\data\test.csv")
df_pre.head(10)

,id,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,165034,15773898,Lucchese,586,France,Female,23.0,2,0.00,2,0.0,1.0,160976.75
1,165035,15782418,Nott,683,France,Female,46.0,2,0.00,1,1.0,0.0,72549.27
2,165036,15807120,K?,656,France,Female,34.0,7,0.00,2,1.0,0.0,138882.09
3,165037,15808905,O'Donnell,681,France,Male,36.0,8,0.00,1,1.0,0.0,113931.57
4,165038,15607314,Higgins,752,Germany,Male,38.0,10,121263.62,1,1.0,0.0,139431.00
5,165039,15672704,Pearson,593,France,Female,22.0,9,0.00,2,0.0,0.0,51907.72
6,165040,15647838,Onyemere,682,Spain,Male,45.0,4,0.00,2,1.0,1.0,157878.67
7,165041,15775307,Hargreaves,539,Spain,Female,47.0,8,0.00,2,1.0,1.0,126784.29
8,165042,15653937,Hsueh,845,France,Female,47.0,3,111096.91,1,1.0,0.0,94978.10
9,165043,15752344,Teng,645,Spain,Male,30.0,5,0.00,2,0.0,1.0,149195.44

In [11]:
# Preprocessing Multi-index Assignments
if "Churn" in df_pre.columns:
    df_pre.set_index(['id', 'CustomerId', 'Surname', 'Churn'], inplace=True)
else:
    df_pre.set_index(['id', 'CustomerId', 'Surname'], inplace=True)
        
df = pd.get_dummies(data=df_pre, columns=list(df_pre.select_dtypes(include=['object'])))
df.head()

C:\Users\Public\Documents\Wondershare\CreatorTemp\ipykernel_13520\1030263204.py:7: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df = pd.get_dummies(data=df_pre, columns=list(df_pre.select_dtypes(include=['object'])))

,,,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain,Gender_Female,Gender_Male
id,CustomerId,Surname,,,,,,,,,,,,,
165034,15773898,Lucchese,586,23.0,2,0.00,2,0.0,1.0,160976.75,True,False,False,True,False
165035,15782418,Nott,683,46.0,2,0.00,1,1.0,0.0,72549.27,True,False,False,True,False
165036,15807120,K?,656,34.0,7,0.00,2,1.0,0.0,138882.09,True,False,False,True,False
165037,15808905,O'Donnell,681,36.0,8,0.00,1,1.0,0.0,113931.57,True,False,False,False,True
165038,15607314,Higgins,752,38.0,10,121263.62,1,1.0,0.0,139431.00,False,True,False,False,True

In [12]:
    # Fetching scaled parameters dynamically
    try:
        scaler = load_scaler(scaler_path)
    except Exception as e:
        st.error(f"Could not load RobustScaler.pkl from default directory: {e}")
        st.stop()

    df_test_scaled_idx = df.index
    df_test_scaled_cols = df.columns
    scaled_values2 = scaler.transform(df)
    
    # Rebuild the DataFrame while keeping the index
    df_test_scaled = pd.DataFrame(scaled_values2, index=df_test_scaled_idx, columns=df_test_scaled_cols)

2026-07-13 00:40:35.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.